version: '3'

services:
    geth:
        image: gethd:latest
        build: .
        container_name: gethd
#        deploy:
#          resources:
#              limits:
#                  cpus: '0.5'
        volumes:
            - ./data:/data
            - ./solidity:/solidity
        ports:
            - "8545:8545"
            - "30303:30303"
        command: >
            bash -c
            "geth --networkid 1111 --nodiscover --maxpeers 0
            --datadir /data --mine --miner.threads=1 --allow-insecure-unlock --unlock 0
            --http --http.addr '0.0.0.0' --http.port 8545 --http.corsdomain '*'
            --http.api 'admin,db,eth,debug,miner,net,shh,txpool,personal,web3'
            --password /data/passwd --verbosity 6 2>> /data/geth.log"
