version: '3'

services:
  openldap:
    image: openldap:latest
    build: .
    container_name: openldap
    ports:
      - 389:389
    volumes:
      - ./data:/data
    command: bash -c "/configs/start.sh"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    depends_on:
      - openldap
    ports:
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
