version: '3'

services:
    frontend:
        image: connection-frontend
        container_name: frontend
        depends_on:
            - db
        ports:
            - 8080:8080
        environment:
            - SQLCONNSTR_FrontendContext=Data Source=db;Initial Catalog=FrontendContext;User ID=sa;Password=FooBar1234!

    backend:
        image: connection-backend
        container_name: backend
        ports:
            - 5000:5000

    db:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: db
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=FooBar1234!
